### PR TITLE
[WIP] Prepare release 1.0.0

### PR DESCRIPTION
**Pull request by glemaitre**
TODO:

- [x] Update to the release version instead of the beta before to merge

### CODE REVIEW

**Comment by glemaitre** [comment]
We are going to release pydicom 1.0.0 so update the recipe.
In the same time I updated the conda smithy.

**Comment by glemaitre** [comment]
@jakirkham I was wondering if we could get some permission for this repository.
We are actually pushing for a release: https://github.com/pydicom/pydicom/issues/523
In case that @arokem is not available, we would like to be able to release pypi and conda forge version at about the same time.

**Comment by jakirkham** [comment]
Sure. Please send a separate PR adding yourself as a maintainer and we can go from there. Can add `[ci skip]` in the commit message as we don’t need to check CIs for that.

**Comment by arokem** [comment]
Looks like you have everything under control here (via #7)? Let me know if there's anything I can do to help. Thanks for your work on pydicom!

**Pull request merged**
